version: '3'

services:
  backend:
    container_name: 'backend'
    build: backend
    command: gunicorn -c "python:config.gunicorn" --reload "src.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - './backend:/backend'
    ports:
      - '5000:5000'

  frontend:
    container_name: 'frontend'
    build: frontend
    command: npm start
    env_file:
      - '.env'
    volumes:
      - './frontend:/frontend'
      - node-modules:/frontend/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  node-modules:
